//! gswitch 配置常量

use std::cell::RefCell;

// ====== 路径注入 (便于测试) ======

thread_local! {
    static CUSTOM_ROOT: RefCell<Option<String>> = const { RefCell::new(None) };
}

/// 仅供测试：将实际根文件系统替换为临时目录
/// 使用 thread-local 存储，支持并行测试
#[doc(hidden)]
pub fn set_root_for_test(root: &str) {
    CUSTOM_ROOT.with(|r| *r.borrow_mut() = Some(root.to_string()));
}

/// 仅供测试：清除测试根目录
#[doc(hidden)]
pub fn clear_root_for_test() {
    CUSTOM_ROOT.with(|r| *r.borrow_mut() = None);
}

/// 解析路径：如果设置了测试根，则拼接前缀；否则原样返回
pub(crate) fn resolve_path(path: &str) -> String {
    CUSTOM_ROOT.with(|r| {
        if let Some(root) = r.borrow().as_ref() {
            format!("{}{}", root.trim_end_matches('/'), path)
        } else {
            path.to_string()
        }
    })
}

/// 是否处于测试模式（路径注入已设置）
pub(crate) fn is_test_mode() -> bool {
    CUSTOM_ROOT.with(|r| r.borrow().is_some())
}

// ====== 全局 dry-run 标志 ======

thread_local! {
    static DRY_RUN: RefCell<Option<bool>> = const { RefCell::new(None) };
}

/// 设置 dry-run 模式（所有写入操作仅打日志，不实际执行）
#[doc(hidden)]
pub fn set_dry_run(enabled: bool) {
    DRY_RUN.with(|r| *r.borrow_mut() = Some(enabled));
}

pub(crate) fn is_dry_run() -> bool {
    DRY_RUN.with(|r| r.borrow().unwrap_or(false))
}

// ====== 缓存 ======

/// GPU 缓存文件路径
pub const CACHE_FILE_PATH: &str = "/var/cache/gswitch/gpu-cache.json";

// ====== PRIME 标志 ======

/// PRIME 独立显卡模式标志文件路径
pub const PRIME_DISCRETE_PATH: &str = "/etc/prime-discrete";

// ====== modprobe 配置 ======

/// GPU 切换用 modprobe 配置路径
pub const MODPROBE_GPU_PATH: &str = "/etc/modprobe.d/gswitch-gpu.conf";

/// 集成模式 modprobe 配置：黑名单 + install 拦截所有 NVIDIA 和 nouveau
///
/// 同时使用 `blacklist` 和 `install … /bin/false` 实现双重保险：
/// - blacklist 阻止 modprobe 按名称加载模块
/// - install 拦截任何尝试加载模块的操作（包括依赖加载）
pub const MODPROBE_INTEGRATED: &str = r#"# Automatically generated by gswitch
blacklist nouveau
blacklist nvidia
blacklist nvidia-drm
blacklist nvidia-modeset
blacklist nvidia-uvm
install nouveau /bin/false
install nvidia /bin/false
install nvidia-drm /bin/false
install nvidia-modeset /bin/false
install nvidia-uvm /bin/false
"#;

// ====== udev 规则 ======

/// 集成模式 udev 规则路径：添加时移除 NVIDIA PCI 设备
pub const UDEV_INTEGRATED_PATH: &str = "/etc/udev/rules.d/50-gswitch-remove-nvidia.rules";

/// 集成模式 udev 规则内容
pub const UDEV_INTEGRATED: &str = r#"# Automatically generated by gswitch
# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{power/control}="auto", ATTR{remove}="1"
# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{power/control}="auto", ATTR{remove}="1"
# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{power/control}="auto", ATTR{remove}="1"
# Remove NVIDIA VGA/3D controller devices
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x03[0-9]*", ATTR{power/control}="auto", ATTR{remove}="1"
"#;

/// 运行时电源管理 udev 规则路径
pub const UDEV_PM_PATH: &str = "/etc/udev/rules.d/80-gswitch-nvidia-pm.rules";

/// 运行时电源管理 udev 规则内容（混合/NVIDIA 模式）
pub const UDEV_PM_CONTENT: &str = r#"# Automatically generated by gswitch
# Remove NVIDIA USB xHCI Host Controller devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{remove}="1"
# Remove NVIDIA USB Type-C UCSI devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{remove}="1"
# Remove NVIDIA Audio devices, if present
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{remove}="1"
# Enable runtime PM for NVIDIA VGA/3D controller devices on driver bind
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="auto"
# Disable runtime PM for NVIDIA VGA/3D controller devices on driver unbind
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="on"
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="on"
"#;

// modeset 配置已合并至 MODPROBE_GPU_PATH 统一管理（参考 system76-power 的单文件模式）
// MODESET_PATH 仅用于清理遗留文件；MODESET_CONTENT 仍用作写入 MODPROBE_GPU_PATH 的基础内容
pub const MODESET_CONTENT: &str = r##"# Automatically generated by gswitch
options nvidia-drm modeset=1
options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
"##;
pub const MODESET_PATH: &str = "/etc/modprobe.d/gswitch-nvidia-modeset.conf";

// ====== initramfs VFIO 配置 ======

/// dracut VFIO 直通 drop-in 配置路径
pub const DRACUT_VFIO_CONF_PATH: &str = "/etc/dracut.conf.d/gswitch-vfio.conf";

/// mkinitcpio VFIO 直通 drop-in 配置路径 (v37+)
pub const MKINITCPIO_VFIO_CONF_PATH: &str = "/etc/mkinitcpio.conf.d/gswitch-vfio.conf";

/// initramfs-tools modules 文件路径 (Debian/Ubuntu)
pub const INITRAMFS_TOOLS_MODULES_PATH: &str = "/etc/initramfs-tools/modules";

// ====== NVIDIA 挂起/休眠电源管理 ======

/// NVIDIA 挂起/休眠的 systemd 服务名称
pub const NVIDIA_SUSPEND_SERVICES: &[&str] = &[
    "nvidia-hibernate.service",
    "nvidia-resume.service",
    "nvidia-suspend.service",
];

/// S0ix 休眠配置：挂起时保留显存
pub const MODPROBE_S0IX: &str = r#"# Preserve video memory through suspend
options nvidia NVreg_EnableS0ixPowerManagement=1
"#;

/// S3 休眠配置：挂起时保留显存
pub const MODPROBE_S3: &str = r#"# Preserve video memory through suspend
options nvidia NVreg_PreserveVideoMemoryAllocations=1
"#;

// ====== X11 PrimaryGPU 配置 ======

/// X11 NVIDIA 配置文件路径
pub const XORG_CONF_NVIDIA_PATH: &str = "/etc/X11/xorg.conf.d/11-nvidia-discrete.conf";

/// X11 NVIDIA 配置的备用路径
pub const XORG_CONF_NVIDIA_FALLBACK_PATH: &str =
    "/usr/share/X11/xorg.conf.d/11-nvidia-discrete.conf";

/// X11 配置内容：设置 NVIDIA 为 PrimaryGPU
pub const XORG_CONF_NVIDIA_CONTENT: &str = r#"# Automatically generated by gswitch
Section "OutputClass"
    Identifier "NVIDIA"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
    Option "PrimaryGPU" "Yes"
EndSection
"#;

// ====== 环境变量配置 ======

/// NVIDIA 环境变量配置文件路径
pub const NV_ENV_PATH: &str = "/etc/environment.d/gswitch-nvidia.conf";

pub const NV_ENV_CONTENT: &str = r#"# Automatically generated by gswitch
__NV_PRIME_RENDER_OFFLOAD=1
__GLX_VENDOR_LIBRARY_NAME=nvidia
__VK_LAYER_NV_optimus=NVIDIA_only
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
"#;

// ====== NVIDIA 专有选项 ======

/// NVIDIA 额外 Xorg OutputClass 路径（ForceCompositionPipeline / Coolbits）
pub const EXTRA_XORG_NVIDIA_PATH: &str = "/etc/X11/xorg.conf.d/10-gswitch-nvidia-extra.conf";

/// X11 额外选择配置片段头部
pub const EXTRA_XORG_HEADER: &str = r#"# Automatically generated by gswitch
Section "OutputClass"
    Identifier "NVIDIA Extra"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
"#;

/// ForceCompositionPipeline 选项
pub const EXTRA_XORG_FORCE_COMP: &str = "    Option \"ForceCompositionPipeline\" \"true\"\n";

/// Coolbits 选项模板（{} 为位掩码值）
pub const EXTRA_XORG_COOLBITS: &str = "    Option \"Coolbits\" \"{}\"\n";

/// X11 OutputClass Section 尾部
pub const EXTRA_XORG_FOOTER: &str = "EndSection\n";

// ====== Display Manager 脚本 ======

/// SDDM Xsetup 路径（需要在 NVIDIA 模式下添加 xrandr 桥接脚本）
pub const SDDM_XSETUP_PATH: &str = "/usr/share/sddm/scripts/Xsetup";

/// SDDM Xsetup 备份路径
pub const SDDM_XSETUP_BAK_PATH: &str = "/usr/share/sddm/scripts/Xsetup.bak";

/// LightDM 脚本路径
pub const LIGHTDM_SCRIPT_PATH: &str = "/etc/lightdm/gswitch-nvidia.sh";

/// LightDM 配置路径
pub const LIGHTDM_CONFIG_PATH: &str = "/etc/lightdm/lightdm.conf.d/20-gswitch-nvidia.conf";

/// LightDM 配置内容
pub const LIGHTDM_CONFIG_CONTENT: &str = r#"# Automatically generated by gswitch
[Seat:*]
display-setup-script=/etc/lightdm/gswitch-nvidia.sh
"#;

/// NVIDIA xrandr 桥接脚本模板（{} 为 iGPU provider 名称：modesetting 或 amdgpu 输出名）
pub const XRANDR_BRIDGE_SCRIPT: &str = r##"#!/bin/sh
# Automatically generated by gswitch
xrandr --setprovideroutputsource "{}" NVIDIA-0
xrandr --auto
for next in $(xrandr --listmonitors | grep -E " *[0-9]+:.*" | cut -d" " -f6); do
  [ -z "$current" ] && current=$next && continue
  xrandr --output "$current" --auto --output "$next" --auto --right-of "$current"
  current=$next
done
"##;

// ====== 机型列表 ======

/// 外接显示器需要 NVIDIA 独立显卡的机型
pub const EXTERNAL_DISPLAY_REQUIRES_NVIDIA: &[&str] = &[
    "addw1", "addw2", "addw3", "addw4", "addw5",
    "addp6", "bonw15", "bonw15-b", "bonw16",
    "gaze14", "gaze15", "gaze16-3050", "gaze16-3060", "gaze16-3060-b",
    "gaze17-3050", "gaze17-3060-b", "gaze20",
    "kudu6", "oryp4", "oryp4-b", "oryp5", "oryp6", "oryp7",
    "oryp8", "oryp9", "oryp10", "oryp11", "oryp12", "oryp13", "oryp14",
    "serw13", "serw14",
];

/// 默认使用独立显卡模式的机型
pub const DEFAULT_DISCRETE_MODELS: &[&str] = &["bonw16"];

// ====== NVIDIA 驱动文档搜索路径 ======

/// /usr/share/doc 下 NVIDIA 相关目录的匹配模式（按发行版）
pub const NVIDIA_DOC_PATTERNS: &[&str] = &[
    "nvidia-driver-",       // Fedora/RHEL (RPM Fusion)
    "nvidia-kernel-common", // Debian/Ubuntu
    "nvidia",               // Arch (nvidia 或 nvidia-dkms)
    "nvidia-dkms",
    "NVIDIA_GLX-1.0",       // 旧版/通用路径
    "nvidia-utils",         // 某些发行版的命名
    "xorg-x11-drv-nvidia",  // RPM Fusion 备选命名
];

/// supported-gpus.json 的绝对路径备用列表（不依赖 /usr/share/doc 扫描）
pub const NVIDIA_GPU_JSON_ALT_PATHS: &[&str] = &[
    "/usr/share/doc/nvidia/supported-gpus.json",
    "/usr/share/doc/nvidia-dkms/supported-gpus.json",
    "/usr/share/doc/NVIDIA_GLX-1.0/supported-gpus.json",
    "/usr/share/nvidia/supported-gpus.json",
    "/usr/local/share/nvidia/supported-gpus.json",
];

// ====== 配置快照（用于切换失败时回滚）======

/// 模式切换过程中可能被修改的文件列表，切换前会做快照
pub const SNAPSHOT_PATHS: &[&str] = &[
    MODPROBE_GPU_PATH,
    MODESET_PATH,
    UDEV_INTEGRATED_PATH,
    UDEV_PM_PATH,
    PRIME_DISCRETE_PATH,
    NV_ENV_PATH,
    XORG_CONF_NVIDIA_PATH,
    XORG_CONF_NVIDIA_FALLBACK_PATH,
    EXTRA_XORG_NVIDIA_PATH,
    DRACUT_VFIO_CONF_PATH,
    MKINITCPIO_VFIO_CONF_PATH,
    INITRAMFS_TOOLS_MODULES_PATH,
    LIGHTDM_SCRIPT_PATH,
    LIGHTDM_CONFIG_PATH,
];

/// 需要在切换前后保存/恢复状态的 systemd 服务
pub const SERVICE_SNAPSHOT_NAMES: &[&str] = &[
    "nvidia-persistenced.service",
    "nvidia-fallback.service",
    "nvidia-hibernate.service",
    "nvidia-resume.service",
    "nvidia-suspend.service",
];